# Generated by Django 3.1.5 on 2021-01-15 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_text', models.CharField(max_length=200)),
                ('user', models.EmailField(max_length=245)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
